### ISSUE TITLE
Comparison to ofoso's

### ISSUE THREAD

**Issue by qubitz** [greghogan/guix-packer#2]
Really excited to see active development on this topic because I'd love the idea of developing remotely with guix. However, I know very little about packer. What improvements have been made compared to [ofosos's guix-packer project](https://github.com/ofosos/guix-packer)?

Edit: corrected url

**Comment by qubitz** [comment]
@greghogan poke 🙃

**Comment by greghogan** [comment]
The two projects do not seem very comparable. Look around, see what you find useful for your workflow.
